### ISSUE TITLE
Brew install failure

### ISSUE THREAD

**Issue by jingibus** [killpack/vin#1]
```
$ brew install killpack/dumb/vin
Cloning into '/usr/local/Library/Taps/killpack/homebrew-dumb'...
remote: Counting objects: 4, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4 (delta 0), reused 4 (delta 0), pack-reused 0
Unpacking objects: 100% (4/4), done.
Checking connectivity... done.
Tapped 1 formula
Error: undefined method `desc' for Formulary::Formulae::Vin:Class
Please report this bug:
    http://git.io/brew-troubleshooting
/usr/local/Library/Taps/killpack/homebrew-dumb/vin.rb:6:in `<class:Vin>'
/usr/local/Library/Taps/killpack/homebrew-dumb/vin.rb:5:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:92:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:92:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:82:in `klass'
/usr/local/Library/Homebrew/formulary.rb:71:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:177:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:200:in `factory'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:46:in `install'
/usr/local/Library/brew.rb:135:in `<main>'
```

**Comment by killpack** [comment]
What version of Homebrew are you using?

**Comment by killpack** [comment]
/ what do you get if you type `brew doctor`?

**Comment by jingibus** [comment]
The answer to the latter question is "a hot mess"

**Comment by killpack** [comment]
Closing due to El Capitan shenanigans.
